version: '3.8'

services:
  flow-masters-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: flow-masters-mcp-dev
    restart: unless-stopped
    ports:
      - "3030:3030"
    environment:
      # API Configuration (локальное приложение Flow Masters)
      - API_URL=http://host.docker.internal:3000
      - API_KEY=${API_KEY:-dev-api-key}
      - API_BASE_PATH=/api
      - API_VERSION=
      
      # MCP Server Configuration
      - PORT=3030
      - HOST=0.0.0.0
      - NODE_ENV=development
      
      # LLM Configuration
      - MODEL_CONTEXT_ENABLED=true
      - ALLOWED_MODELS=*
      - MAX_TOKENS=8192
      - CONTEXT_WINDOW=4096
      
      # Cache Configuration
      - CACHE_ENABLED=true
      - CACHE_TTL=60
      - CACHE_MAX_SIZE=50
      
      # Auto Update Settings
      - AUTO_UPDATE=false
      - UPDATE_CHECK_INTERVAL=300
      
      # Logging
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./config.json:/app/config.json:ro
      - /app/node_modules
    networks:
      - mcp-dev-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/mcp/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-dev-network:
    driver: bridge