version: '3.8'

services:
  mcp:
    build:
      context: ..
      dockerfile: flow-masters-mcp/Dockerfile.standalone
    container_name: flow-masters-mcp
    ports:
      - '3030:3030'
    environment:
      - PORT=3030
      - HOST=0.0.0.0
      - API_URL=http://host.docker.internal:3000
      - API_KEY=${PAYLOAD_SECRET:-08c93b8544167b018efded89}
      - AUTO_UPDATE=true
      - UPDATE_CHECK_INTERVAL=60
      - API_BASE_PATH=/api
      - API_VERSION=v1
      - MODEL_CONTEXT_ENABLED=true
      - ALLOWED_MODELS=*
      - MAX_TOKENS=8192
      - CONTEXT_WINDOW=4096
      - CACHE_ENABLED=true
      - CACHE_TTL=3600
    volumes:
      - mcp_data:/app/data
    restart: always
    # Use host.docker.internal to connect to services on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mcp_data:
    driver: local
