export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // The component should just return its children, as <html> and <body>
  // are already provided by the root layout.
  return children
}
